version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/vendor/bundle
    ports:
      - 127.0.0.1:9292:9292
    environment:
      - SESSION_SECRET=1f4318d9a2eaea28a0f0195ec0b7a304e2388375b95be995467ae05b0cc2c93c
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: HskXyct6
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
  redis:
    image: redis:7.0
